#!/usr/bin/python3

# script to generate stats to plot in venn_diagramm.svg with circles of the same size. Generates venns for 3 organs and between two organs of the same species
# This script takes as input, the outputs generated by clustering_analysis_stats.py and searches for common ACC in those files.

import sys

Filegrab = sys.argv[1:] 



L_1 = []
L_2 = []
L_3 = []
L_4 = []
L_5 = []
L_6 = []
x = 0
for infile in Filegrab:
	file_handle = open(infile)
	x += 1
	print(infile)
	for line in file_handle:
		if x == 1:
			L_1.append(line.strip())
		elif x == 2:
			L_2.append(line.strip())
		elif x == 3:
			L_3.append(line.strip())
		elif x == 4:
			L_4.append(line.strip())
		elif x == 5:
			L_5.append(line.strip())
		elif x == 6:
			L_6.append(line.strip())
		else:
			print("error: too much infiles, script is limited to 6 input files... but feel free to change it anytime")

			
print("First venn3 diagramm")
print(str(len(L_1)) + " contigs in " + Filegrab[0])
print(str(len(L_2)) + " contigs in " + Filegrab[1])
print(str(len(L_3)) + " contigs in " + Filegrab[2] + "\n")

print(str(len(list(set(L_1) & set(L_2)))) + " contigs common to " + Filegrab[0] + " and " + Filegrab[1])
print(str(len(list(set(L_2) & set(L_3)))) + " contigs common to " + Filegrab[1] + " and " + Filegrab[2])
print(str(len(list(set(L_1) & set(L_3)))) + " contigs common to " + Filegrab[0] + " and " + Filegrab[2])
print(str(len(list(set(L_1) & set(L_2) & set(L_3)))) + " contigs common to " + Filegrab[0]+ " and " + Filegrab[1] + " and " + Filegrab[2] + "\n")

print("Second venn3 diagramm")
print(str(len(L_4)) + " contigs in " + Filegrab[3])
print(str(len(L_5)) + " contigs in " + Filegrab[4])
print(str(len(L_6)) + " contigs in " + Filegrab[5] + "\n")

print(str(len(list(set(L_4) & set(L_5)))) + " contigs common to " + Filegrab[3] + " and " + Filegrab[4])
print(str(len(list(set(L_5) & set(L_6)))) + " contigs common to " + Filegrab[4] + " and " + Filegrab[5])
print(str(len(list(set(L_4) & set(L_6)))) + " contigs common to " + Filegrab[3] + " and " + Filegrab[5])
print(str(len(list(set(L_4) & set(L_5) & set(L_6)))) + " contigs common to " + Filegrab[3]+ " and " + Filegrab[4] + " and " + Filegrab[5] +"\n")

print("venn2 diagramms")
print(str(len(list(set(L_1) & set(L_4)))) + " contigs common to " + Filegrab[0] + " and " + Filegrab[3])
print(str(len(list(set(L_2) & set(L_5)))) + " contigs common to " + Filegrab[1] + " and " + Filegrab[4])
print(str(len(list(set(L_3) & set(L_6)))) + " contigs common to " + Filegrab[2] + " and " + Filegrab[5])



